name: esp32-firmware

on:
  workflow_dispatch:
  push:
    tags:
      - "esp32-v*"

jobs:
  build-esp32:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest
    defaults:
      run:
        shell: bash
        working-directory: esp32
    steps:
      - uses: actions/checkout@v4

      - name: Build (ESP-IDF)
        run: |
          git config --global --add safe.directory "*"
          idf.py set-target esp32
          idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-build
          path: |
            esp32/build/*.bin
            esp32/build/*.elf
            esp32/build/*.map
            esp32/build/bootloader/*.bin
            esp32/build/partition_table/*.bin
